# Generated by Django 4.2 on 2023-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYU_FORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactandaddress',
            name='PhoneNumber1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contactandaddress',
            name='PhoneNumber2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='ZipCode',
            field=models.IntegerField(),
        ),
    ]
